/*
 * NodeInfos.h
 *
 *  Created on: Sep 7, 2024
 *      Author: georg
 */

#ifndef INC_NODEINFOS_H_
#define INC_NODEINFOS_H_

typedef enum
{
	NODE_ID_LAMARR_RCU_V2 = 29,
	NODE_ID_LAMARR_FUEL_ECU = 31,
	NODE_ID_LAMARR_OX_ECU = 32,
	NODE_ID_LAMARR_ENGINE_ECU = 33,
	NODE_ID_LAMARR_GSE_PNEU_0 = 34,
	NODE_ID_LAMARR_GSE_PNEU_1 = 35,
	NODE_ID_LAMARR_GSE_ELEC_IOB0 = 36,
	NODE_ID_LAMARR_GSE_ELEC_IOB1 = 37,
	NODE_ID_LAMARR_GSE_ELEC_BOB = 38,
	NODE_ID_LAMARR_GSE_PNEU_2 = 39,
	NODE_ID_LAMARR_LCB = 8
} NodeId_t;

typedef struct
{
	const NodeId_t node;
	const int channel;
} ChannelLookUpEntry;

typedef enum
{
	ECU_LAMARR_PRESS0 = 0,
	ECU_LAMARR_PRESS1,
	ECU_LAMARR_PRESS2,
	ECU_LAMARR_PRESS3,
	ECU_LAMARR_TEMP0,
	ECU_LAMARR_TEMP1,
	ECU_LAMARR_SERVO0,
	ECU_LAMARR_SERVO1,
	ECU_LAMARR_IGNITER0,
	ECU_LAMARR_IGNITER0_CONT,
	ECU_LAMARR_IGNITER1,
	ECU_LAMARR_IGNITER1_CONT,
	ECU_LAMARR_IGNITER2,
	ECU_LAMARR_IGNITER2_CONT,
	ECU_LAMARR_IGNITER3,
	ECU_LAMARR_IGNITER3_CONT,
	ECU_LAMARR_PI_CONTROLLER,
	ECU_LAMARR_ROCKET,
	ECU_LAMARR_SENSE_5V,
	ECU_LAMARR_SENSE_12V,
	ECU_LAMARR_SENSE_12VA

}ECU_LAMARR_CHANNEL_IDS;

typedef enum
{
	LCB_INPUT0 = 0,
	LCB_INPUT1,
	LCB_INPUT2,
	LCB_INPUT3,
	LCB_INPUT4,
	LCB_INPUT5,
	LCB_INPUT6,
	LCB_INPUT7

}LCB_CHANNEL_IDS;


typedef enum
{
	RCUv2_SENSE_5V = 0,
	RCUv2_SENSE_12V,
	RCUv2_BARO,
	RCUv2_ACCEL_X,
	RCUv2_ACCEL_Y,
	RCUv2_ACCEL_Z,
	RCUv2_GYRO_X,
	RCUv2_GYRO_Y,
	RCUv2_GYRO_Z,
	RCUv2_GNSS_LONG,
	RCUv2_GNSS_LAT,
	RCUv2_GNSS_ALT,
	RCUv2_GNSS_STATUS,
	RCUv2_OUT0,
	RCUv2_OUT1,
	RCUv2_OUT2,
	RCUv2_OUT3


}RCUv2_CHANNEL_IDS;
typedef enum
{

	DEVICE_ID_FUEL_ECU_PRESSURANT_VALVE,
	DEVICE_ID_FUEL_ECU_VENT_VALVE,
	DEVICE_ID_FUEL_ECU_TANK_PRESSURE,
	DEVICE_ID_FUEL_ECU_PRESSURANT_PRESSURE,
	DEVICE_ID_FUEL_ECU_PRESSURE_CONTROLLER,
	DEVICE_ID_FUEL_ECU_ROCKET_CHANNEL,

	DEVICE_ID_OX_ECU_PRESSURANT_VALVE,
	DEVICE_ID_OX_ECU_VENT_VALVE,
	DEVICE_ID_OX_ECU_TANK_PRESSURE,
	DEVICE_ID_OX_ECU_PRESSURANT_PRESSURE,
	DEVICE_ID_OX_ECU_PRESSURE_CONTROLLER,
	DEVICE_ID_OX_ECU_ROCKET_CHANNEL,

	DEVICE_ID_ENGINE_ECU_FUEL_MAIN_VALVE,
	DEVICE_ID_ENGINE_ECU_OX_MAIN_VALVE,
	DEVICE_ID_ENGINE_ECU_FUEL_VENTURI_PRESSURE,
	DEVICE_ID_ENGINE_ECU_OX_VENTURI_PRESSURE,
	DEVICE_ID_ENGINE_ECU_CHAMBER_PRESSURE,
	DEVICE_ID_ENGINE_ECU_INTERNAL_IGNITER,
	DEVICE_ID_ENGINE_ECU_ROCKET_CHANNEL,

	DEVICE_ID_GSE_PNEU_0_PRESSURANT_TANKING_VALVE,
	DEVICE_ID_GSE_PNEU_0_PRESSURANT_VENT_VALVE,
	DEVICE_ID_GSE_PNEU_0_OX_TANKING_VALVE,
	DEVICE_ID_GSE_PNEU_0_PRESSURANT_TANKING_VALVE_FEEDBACK,
	DEVICE_ID_GSE_PNEU_0_PRESSURANT_VENT_VALVE_FEEDBACK,
	DEVICE_ID_GSE_PNEU_0_OX_TANKING_VALVE_FEEDBACK,
	DEVICE_ID_GSE_PNEU_0_DEWAR_PRESS_VALVE,
	
	DEVICE_ID_GSE_PNEU_1_PNEU_PRESS_IN,
	DEVICE_ID_GSE_PNEU_1_DEWAR_PRESSURE,
	DEVICE_ID_GSE_PNEU_1_VENTILINSEL_PRESSURE,
	DEVICE_ID_GSE_PNEU_1_HOLDDOWN,
	DEVICE_ID_GSE_PNEU_1_OX_DECOUPLER_FEEDBACK,

	DEVICE_ID_GSE_ELEC_IOB_OX_DECOUPLER,
	DEVICE_ID_GSE_ELEC_IOB_STRONGBACK,
	DEVICE_ID_GSE_ELEC_IOB_EXTERNAL_IGNITER,

	
	DEVICE_ID_GSE_ELEC_BOB_LAMP_RED,
	DEVICE_ID_GSE_ELEC_BOB_LAMP_GREEN,

	DEVICE_ID_LCB_ROCKET_WEIGHT,
	DEVICE_ID_LCB_DEWAR_WEIGHT,
	DEVICE_ID_RCU_CAM_1,
	DEVICE_ID_RCU_CAM_2,
	DEVICE_ID_RCU_GENERIC_CHANNEL


}DeviceIds;

extern const ChannelLookUpEntry channellookUp[];
//#define LAMARR_ECU_NODE_ID 5
//#define LAMARR_ECU_NODE_ID NODE_ID_LAMARR_OX_ECU
//#define LAMARR_ECU_NODE_ID NODE_ID_LAMARR_FUEL_ECU
//#define LAMARR_ECU_NODE_ID NODE_ID_LAMARR_GSE_PNEU_0
//#define LAMARR_ECU_NODE_ID NODE_ID_LAMARR_GSE_PNEU_1
//#define LAMARR_ECU_NODE_ID NODE_ID_LAMARR_GSE_PNEU_2
//#define LAMARR_ECU_NODE_ID NODE_ID_LAMARR_GSE_ELEC_IOB0
//#define LAMARR_ECU_NODE_ID NODE_ID_LAMARR_GSE_ELEC_IOB1
//#define LAMARR_ECU_NODE_ID NODE_ID_LAMARR_GSE_ELEC_BOB

#define IS_MAIN_ECU


#ifdef IS_MAIN_ECU
	#ifdef LAMARR_ECU_NODE_ID
		#error config error
	#endif
	#define LAMARR_ECU_NODE_ID NODE_ID_LAMARR_ENGINE_ECU
#else
	#define IS_NOT_MAIN_ECU
#endif

#endif /* INC_NODEINFOS_H_ */
